import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Dashboard from '../components/layout/dashboard'


export default function Home() {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? <Dashboard /> : <div>Guest</div>}

      {/* if not logged in show guest home page */}
      {/* if logged in show authenticated home page */}


    </div>
  )
}
